name: Fetch Data

on:
  schedule:
    - cron: '0 0 * * *'  # Exécute le workflow tous les jours à minuit (UTC)
  workflow_dispatch:   # Permet de déclencher manuellement le workflow

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install requests pandas

      - name: Run fetch_data.py
        run: |
          python scripts/fetch_data.py

      - name: Commit updated data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/matchs.csv
          git commit -m "Mise à jour automatique des données" || echo "Aucune modification"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
